# 1章 Python 入門
## 1.3 Pythonインタプリタ
## 1.3.1 算術計算

In [1]:
1 - 2

-1

In [2]:
4 * 5

20

In [3]:
7 / 5

1.4

In [4]:
3 ** 2

9

## 1.3.2 データ型

In [5]:
type(10)

int

In [6]:
type(2.718)

float

In [7]:
type("hello")

str

## 1.3.3 変数

In [8]:
x = 10
print(x)

10


In [9]:
x = 100
print(x)

100


In [10]:
y = 3.14
x * y

314.0

In [11]:
type(x * y)

float

## 1.3.4 リスト

In [12]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [13]:
len(a)

5

In [14]:
a[0]

1

In [15]:
a[4]

5

In [16]:
a[4] = 99
print(a)

[1, 2, 3, 4, 99]


In [17]:
a[0:2]

[1, 2]

In [18]:
a[1:]

[2, 3, 4, 99]

In [19]:
a[:3]

[1, 2, 3]

In [20]:
a[:-1]

[1, 2, 3, 4]

In [21]:
a[:-2]

[1, 2, 3]

## 1.3.5 ディクショナリ

In [22]:
me = {"height": 180}
me["height"]

180

In [23]:
me["weight"] = 70
print(me)

{'height': 180, 'weight': 70}


## 1.3.6 ブーリアン

In [24]:
hungry = True
sleepy = False
type(hungry)

bool

In [25]:
not hungry

False

In [26]:
hungry and sleepy

False

In [27]:
hungry or sleepy

True

In [28]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [29]:
hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm not sleepy")

I'm not hungry
I'm not sleepy


## 1.3.8 for 文

In [30]:
for i in [1, 2, 3]:
    print(i)

1
2
3


## 1.3.9 関数

In [31]:
def hello():
    print("Hello World!")

hello()

Hello World!


In [32]:
def hello(object):
    print("Hello " + object + "!")

hello("cat")

Hello cat!


## 1.4 Python スクリプトファイル
## 1.4.1 ファイルに保存

In [33]:
%run hungry.py

I'm hungury!


## 1.4.2 クラス

In [34]:
%run man.py

Initialized!
HelloDavid!!
Good-byeDavid!!


## 1.5 NumPy
## 1.5.1 NumPy のインポート

In [35]:
import numpy as np

## 1.5.2 NumPy 配列の生成

In [36]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[ 1.  2.  3.]


In [37]:
type(x)

numpy.ndarray

## 1.5.3 NumPy の算術計算

In [38]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([ 3.,  6.,  9.])

In [39]:
x - y

array([-1., -2., -3.])

In [40]:
x * y

array([  2.,   8.,  18.])

In [41]:
x / y

array([ 0.5,  0.5,  0.5])

In [42]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([ 0.5,  1. ,  1.5])

## 1.5.4 NumPy の N 次元配列

In [43]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [44]:
A.shape

(2, 2)

In [45]:
A.dtype

dtype('int64')

In [46]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [47]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [48]:
print(A)

[[1 2]
 [3 4]]


In [49]:
A * 10

array([[10, 20],
       [30, 40]])

## 1.5.5 ブロードキャスト

In [50]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

## 1.5.6 要素へのアクセス

In [51]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [52]:
X[0]

array([51, 55])

In [53]:
X[0][1]

55

In [54]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [55]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [56]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [57]:
X > 15

array([ True,  True, False,  True, False, False], dtype=bool)

In [58]:
X[X>15]

array([51, 55, 19])